# Generated by Django 3.2.12 on 2024-06-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='AccessoryTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'AccessoryTypes',
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street_no', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_employed', models.DateField()),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_group_members', models.IntegerField()),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Horses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=50)),
                ('eye_color', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('origin', models.CharField(max_length=255)),
                ('hairstyle', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Horses',
            },
        ),
        migrations.CreateModel(
            name='Licences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_level', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Licences',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='horses_database.addresses')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='members', to='horses_database.licences')),
            ],
            options={
                'db_table': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='horses_database.addresses')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='horses_database.employees')),
            ],
            options={
                'db_table': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant_place', models.IntegerField(blank=True, null=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses_database.members')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses_database.tournaments')),
            ],
            options={
                'db_table': 'Tournament_Participants',
            },
        ),
        migrations.CreateModel(
            name='Stables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='horses_database.addresses')),
            ],
            options={
                'db_table': 'Stables',
            },
        ),
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_consent', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='horses_database.groups')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='horses_database.horses')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses_database.members')),
            ],
            options={
                'db_table': 'Riders',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('speciality', models.CharField(max_length=255)),
                ('coaching_licence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='coaching_positions', to='horses_database.licences')),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='positions', to='horses_database.licences')),
            ],
            options={
                'db_table': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses_database.employees')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses_database.positions')),
            ],
            options={
                'db_table': 'Positions_History',
            },
        ),
        migrations.CreateModel(
            name='HorseAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses_database.accessories')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses_database.horses')),
            ],
            options={
                'db_table': 'Horses_Accessories',
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses_database.members'),
        ),
        migrations.AddField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='horses_database.positions'),
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses_database.groups')),
                ('stable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horses_database.stables')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='classes', to='horses_database.employees')),
            ],
            options={
                'db_table': 'Classes',
            },
        ),
        migrations.AddField(
            model_name='accessories',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='horses_database.accessorytypes'),
        ),
    ]
